In [4]:
#建立list
a = [1,3,5,7,9]
b = [2,4,6,8,10]
result1 = []
result2 = []
for i in range(5):
    result1.append(a[i]*2)
    result2.append(a[i]+b[i])
print(result1)
print(result2)

[2, 6, 10, 14, 18]
[3, 7, 11, 15, 19]


In [4]:
import numpy as np

#透過list建立ndArray

a_array = np.array([1,3,5,7,9])
a_array*2

b_array = np.array([2,4,6,8,10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [3]:
#使用python建立5個亂數元素的list
import random

#list comprehension
[random.randint(50,100) for _ in range(5)]

[97, 80, 67, 57, 85]

In [7]:
#使用numpy建立亂數
import numpy as np
np.random.randint(50,high=100,size=5)

array([62, 97, 59, 99, 82])

In [6]:
np.random.randint(50,high=100,size=(50,5))

array([[57, 53, 69, 94, 67],
       [62, 87, 70, 51, 78],
       [50, 87, 78, 72, 56],
       [50, 56, 77, 54, 85],
       [72, 62, 52, 68, 90],
       [77, 50, 61, 72, 70],
       [56, 90, 63, 66, 55],
       [78, 92, 60, 75, 55],
       [64, 96, 59, 91, 69],
       [67, 65, 83, 94, 63],
       [63, 57, 93, 89, 70],
       [64, 93, 85, 56, 79],
       [99, 89, 73, 88, 79],
       [73, 66, 61, 64, 82],
       [71, 51, 61, 88, 56],
       [57, 87, 69, 88, 64],
       [56, 53, 91, 58, 66],
       [75, 84, 60, 66, 84],
       [93, 77, 54, 79, 65],
       [70, 91, 62, 85, 73],
       [54, 93, 71, 59, 62],
       [65, 84, 59, 64, 54],
       [78, 50, 93, 59, 51],
       [77, 95, 86, 95, 74],
       [63, 74, 70, 73, 83],
       [83, 82, 69, 69, 60],
       [67, 97, 82, 60, 69],
       [72, 98, 77, 61, 67],
       [86, 65, 56, 78, 69],
       [72, 81, 73, 85, 68],
       [65, 88, 91, 63, 92],
       [55, 72, 96, 61, 68],
       [68, 97, 88, 83, 58],
       [56, 60, 80, 60, 91],
       [82, 80